# Generated by Django 4.0.5 on 2022-06-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_news_options_news_photo_alter_category_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Пицца', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name': 'Начинка', 'verbose_name_plural': 'Начинки'},
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='title',
            field=models.CharField(default=str, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='testapp.topping'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Вес (гр.)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topping',
            name='features',
            field=models.CharField(blank=True, choices=[('hot', 'острый'), ('vegan', 'вегетерианский')], default=None, max_length=100, verbose_name='Свойства'),
        ),
        migrations.AddField(
            model_name='topping',
            name='title',
            field=models.CharField(default=str, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
